FROM node:22
WORKDIR /app

# Copy package.json and tsconfig.json
COPY package*.json tsconfig*.json ./

# Install all dependencies
RUN npm install

# Copy backend source
COPY ./src/backend ./backend
WORKDIR /app/backend

EXPOSE 5000

# Run the backend
CMD ["npx", "ts-node", "server.ts"]
