FROM node:22 AS build
WORKDIR  /app

# Copy package and config files
COPY package*.json tsconfig*.json vite.config.ts ./

# Install dependencies
RUN npm install

# Copy frontend source directly into /app
COPY ./src/frontend/ ./frontend

# Build
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
